#!/usr/bin/env bash
# Prove stack skills for a slug are **installed and ready to Read**.
# Writes projects/<slug>/factory/stack-skills.manifest with **engine-root-relative**
# paths (never absolute host paths). Runtime projects/* are gitignored; refuse `_template`.
#
# Usage:
#   bash scripts/verify_stack_skills.sh <slug>
#   bash scripts/verify_stack_skills.sh <slug> --install   # sync then verify
#   bash scripts/verify_stack_skills.sh <slug> --print     # print manifest paths
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SLUG="${1:-}"
INSTALL=0
PRINT=0
for arg in "${@:2}"; do
  case "$arg" in
    --install) INSTALL=1 ;;
    --print) PRINT=1 ;;
  esac
done

if [[ -z "$SLUG" ]]; then
  echo "Usage: bash scripts/verify_stack_skills.sh <slug> [--install] [--print]" >&2
  exit 2
fi

if [[ "$SLUG" == "_template" ]]; then
  echo "STACK_SKILLS_FAIL refuse writing manifest under projects/_template" >&2
  exit 1
fi

YAML="$ROOT/projects/$SLUG/project.yaml"
if [[ ! -f "$YAML" ]]; then
  echo "STACK_SKILLS_FAIL missing $YAML" >&2
  exit 1
fi

if [[ "$INSTALL" -eq 1 ]]; then
  bash "$ROOT/scripts/sync_stack_skills.sh" "$SLUG"
fi

STACK_BLOB="$(
  awk '
    /^stack:[[:space:]]*$/ { in_stack=1; next }
    in_stack && /^[a-zA-Z0-9_]+:/ && $0 !~ /^[[:space:]]/ { exit }
    in_stack { print }
  ' "$YAML" | tr '\n' ' '
)"
STACK_LC="$(printf '%s' "$STACK_BLOB" | tr '[:upper:]' '[:lower:]')"

need() { printf '%s' "$STACK_LC" | grep -Eq "$1"; }

AGENTS="$ROOT/.agents/skills"
MANIFEST_DIR="$ROOT/projects/$SLUG/factory"
MANIFEST="$MANIFEST_DIR/stack-skills.manifest"
mkdir -p "$MANIFEST_DIR"

# Expected primary SKILL.md paths (name → relative under .agents/skills)
EXPECTED=()
if need 'asp\.net|c#|\.net|dotnet'; then
  EXPECTED+=("dotnet-webapi/SKILL.md")
  EXPECTED+=("dotnet-run-tests/SKILL.md")
fi
if need 'angular'; then
  EXPECTED+=("angular-component/SKILL.md")
  EXPECTED+=("angular-forms/SKILL.md")
fi
if need 'ionic'; then
  EXPECTED+=("ionic-angular/SKILL.md")
fi
if need 'sql server|mssql|t-sql|stored procedure'; then
  EXPECTED+=("mssql-server/SKILL.md")
fi
if need 'supabase'; then
  EXPECTED+=("supabase/SKILL.md")
fi

MISSING=0
: > "$MANIFEST"
{
  echo "# stack-skills.manifest — generated by verify_stack_skills.sh"
  echo "# Paths are relative to the engine repo root. Agent MUST Read each SKILL.md"
  echo "# before implementing stack-related code for slug=$SLUG"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
} >> "$MANIFEST"

for rel in "${EXPECTED[@]}"; do
  eng_rel=".agents/skills/$rel"
  if [[ -f "$ROOT/$eng_rel" ]]; then
    echo "$eng_rel" >> "$MANIFEST"
    echo "STACK_SKILL_OK $rel"
  else
    echo "STACK_SKILL_MISSING $rel" >&2
    MISSING=1
  fi
done

# Project overrides always scanned (even when no marketplace packs matched)
PROJ_SKILLS_REL="projects/$SLUG/.cursor/skills"
if [[ -d "$ROOT/$PROJ_SKILLS_REL" ]]; then
  while IFS= read -r -d '' f; do
    rel_path="${f#"$ROOT"/}"
    echo "$rel_path" >> "$MANIFEST"
    echo "STACK_SKILL_OK project:$(basename "$(dirname "$f")")"
  done < <(find "$ROOT/$PROJ_SKILLS_REL" -name SKILL.md -print0 2>/dev/null || true)
fi

if [[ "$PRINT" -eq 1 ]]; then
  echo "----- manifest $MANIFEST -----"
  cat "$MANIFEST"
fi

if [[ "$MISSING" -ne 0 ]]; then
  echo "STACK_SKILLS_FAIL {\"slug\":\"$SLUG\",\"hint\":\"bash scripts/sync_stack_skills.sh $SLUG && bash scripts/verify_stack_skills.sh $SLUG\"}" >&2
  exit 1
fi

COUNT="$(grep -cE 'SKILL\.md$' "$MANIFEST" || true)"
NOTE=""
if [[ ${#EXPECTED[@]} -eq 0 ]]; then
  NOTE=',"note":"no marketplace packs matched"'
fi
echo "STACK_SKILLS_OK {\"slug\":\"$SLUG\",\"packs\":$COUNT,\"manifest\":\"projects/$SLUG/factory/stack-skills.manifest\"$NOTE}"
echo "STACK_SKILLS_USE Read every SKILL.md listed in projects/$SLUG/factory/stack-skills.manifest (engine-root relative) before stack-related implement."
