#!/usr/bin/env bash
# Prove stack skills for a slug are **installed and ready to Read**.
# Writes projects/<slug>/factory/stack-skills.manifest (gitignored via projects/*).
#
# Usage:
#   bash scripts/verify_stack_skills.sh <slug>
#   bash scripts/verify_stack_skills.sh <slug> --install   # sync then verify
#   bash scripts/verify_stack_skills.sh <slug> --print     # print manifest paths
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

SLUG="${1:-}"
INSTALL=0
PRINT=0
for arg in "${@:2}"; do
  case "$arg" in
    --install) INSTALL=1 ;;
    --print) PRINT=1 ;;
  esac
done

if [[ -z "$SLUG" ]]; then
  echo "Usage: bash scripts/verify_stack_skills.sh <slug> [--install] [--print]" >&2
  exit 2
fi

YAML="$ROOT/projects/$SLUG/project.yaml"
if [[ ! -f "$YAML" ]]; then
  echo "STACK_SKILLS_FAIL missing $YAML" >&2
  exit 1
fi

if [[ "$INSTALL" -eq 1 ]]; then
  bash "$ROOT/scripts/sync_stack_skills.sh" "$SLUG"
fi

STACK_BLOB="$(
  awk '
    /^stack:[[:space:]]*$/ { in_stack=1; next }
    in_stack && /^[a-zA-Z0-9_]+:/ && $0 !~ /^[[:space:]]/ { exit }
    in_stack { print }
  ' "$YAML" | tr '\n' ' '
)"
STACK_LC="$(printf '%s' "$STACK_BLOB" | tr '[:upper:]' '[:lower:]')"

need() { printf '%s' "$STACK_LC" | grep -Eq "$1"; }

AGENTS="$ROOT/.agents/skills"
MANIFEST_DIR="$ROOT/projects/$SLUG/factory"
MANIFEST="$MANIFEST_DIR/stack-skills.manifest"
mkdir -p "$MANIFEST_DIR"

# Expected primary SKILL.md paths (name → relative under .agents/skills)
EXPECTED=()
if need 'asp\.net|c#|\.net|dotnet'; then
  EXPECTED+=("dotnet-webapi/SKILL.md")
  EXPECTED+=("dotnet-run-tests/SKILL.md")
fi
if need 'angular'; then
  EXPECTED+=("angular-component/SKILL.md")
  EXPECTED+=("angular-forms/SKILL.md")
fi
if need 'ionic'; then
  EXPECTED+=("ionic-angular/SKILL.md")
fi
if need 'sql server|mssql|t-sql|stored procedure'; then
  EXPECTED+=("mssql-server/SKILL.md")
fi
if need 'supabase'; then
  EXPECTED+=("supabase/SKILL.md")
fi

if [[ ${#EXPECTED[@]} -eq 0 ]]; then
  echo "STACK_SKILLS_OK {\"slug\":\"$SLUG\",\"packs\":0,\"note\":\"no stack packs matched\"}"
  : > "$MANIFEST"
  exit 0
fi

MISSING=0
: > "$MANIFEST"
{
  echo "# stack-skills.manifest — generated by verify_stack_skills.sh"
  echo "# Agent MUST Read each SKILL.md below before implementing stack-related code for slug=$SLUG"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
} >> "$MANIFEST"

for rel in "${EXPECTED[@]}"; do
  abs="$AGENTS/$rel"
  if [[ -f "$abs" ]]; then
    echo "$abs" >> "$MANIFEST"
    echo "STACK_SKILL_OK $rel"
  else
    echo "STACK_SKILL_MISSING $rel" >&2
    MISSING=1
  fi
done

# Optional product overrides
PROJ_SKILLS="$ROOT/projects/$SLUG/.cursor/skills"
if [[ -d "$PROJ_SKILLS" ]]; then
  while IFS= read -r -d '' f; do
    echo "$f" >> "$MANIFEST"
    echo "STACK_SKILL_OK project:$(basename "$(dirname "$f")")"
  done < <(find "$PROJ_SKILLS" -name SKILL.md -print0 2>/dev/null || true)
fi

if [[ "$PRINT" -eq 1 ]]; then
  echo "----- manifest $MANIFEST -----"
  cat "$MANIFEST"
fi

if [[ "$MISSING" -ne 0 ]]; then
  echo "STACK_SKILLS_FAIL {\"slug\":\"$SLUG\",\"hint\":\"bash scripts/sync_stack_skills.sh $SLUG && bash scripts/verify_stack_skills.sh $SLUG\"}" >&2
  exit 1
fi

COUNT="$(grep -c '/SKILL.md$' "$MANIFEST" || true)"
echo "STACK_SKILLS_OK {\"slug\":\"$SLUG\",\"packs\":$COUNT,\"manifest\":\"$MANIFEST\"}"
echo "STACK_SKILLS_USE Read every SKILL.md listed in $MANIFEST before stack-related implement (do not skip)."
